package com.txt_nifty.sketch.flmml

interface IChannel {
    fun setExpression(ex: Int)
    fun setVelocity(velocity: Int)
    fun setNoteNo(noteNo: Int, tie: Boolean)
    fun setNoteNo(noteNo: Int) //setNoteNo(noteNo,true);
    fun setDetune(detune: Int)
    fun noteOn(noteNo: Int, velocity: Int)
    fun noteOff(noteNo: Int)
    fun close()
    fun setNoiseFreq(frequency: Double)
    fun setForm(form: Int, subform: Int)
    fun setEnvelope1Atk(attack: Int)
    fun setEnvelope1Point(time: Int, level: Int)
    fun setEnvelope1Rel(release: Int)
    fun setEnvelope2Atk(attack: Int)
    fun setEnvelope2Point(time: Int, level: Int)
    fun setEnvelope2Rel(release: Int)
    fun setPWM(pwm: Int)
    fun setPan(pan: Int)
    fun setFormant(vowel: Int)
    fun setLFOFMSF(form: Int, subform: Int)
    fun setLFODPWD(depth: Int, freq: Double)
    fun setLFODLTM(delay: Int, time: Int)
    fun setLFOTarget(target: Int)
    fun setLpfSwtAmt(swt: Int, amt: Int)
    fun setLpfFrqRes(frq: Int, res: Int)
    fun setVolMode(m: Int)
    fun setInput(i: Int, p: Int)
    fun setOutput(o: Int, p: Int)
    fun setRing(s: Int, p: Int)
    fun setSync(m: Int, p: Int)
    fun setPortamento(depth: Int, len: Double)
    fun setMidiPort(mode: Int)
    fun setMidiPortRate(rate: Double)
    fun setPortBase(base: Int)
    fun setSoundOff()
    val voiceCount: Int
    fun setVoiceLimit(voiceLimit: Int)
    fun setHwLfo(data: Int)
    fun reset()
    fun getSamples(samples: DoubleArray?, max: Int, start: Int, delta: Int)
}